# Generated by Django 3.2.10 on 2022-09-02 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gettingApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('postnom', models.CharField(max_length=50, verbose_name='post nom')),
                ('prenom', models.CharField(blank=True, max_length=50, null=True, verbose_name='prenoom')),
                ('genre', models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1, null=True)),
                ('lieu', models.CharField(blank=True, max_length=80, null=True, verbose_name='lieu de naissance')),
                ('date', models.DateField(null=True, verbose_name='date de naissance')),
                ('photo', models.ImageField(null=True, upload_to=gettingApp.models.changname)),
                ('nom_pere', models.CharField(blank=True, max_length=100, null=True, verbose_name='nom du père')),
                ('nom_mere', models.CharField(blank=True, max_length=100, null=True, verbose_name='nom de la mère')),
            ],
        ),
        migrations.CreateModel(
            name='Hystorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('request', models.CharField(max_length=100, null=True)),
                ('nombre_requete', models.IntegerField(default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCondamnation', models.DateField(verbose_name='date de condamnation')),
                ('organeCondamnatoire', models.CharField(choices=[('cours', 'cours'), ('tribunal', 'tribunal')], max_length=10, verbose_name='cours ou tribunaux')),
                ('NatureCrime', models.CharField(choices=[('contravention', 'contravention'), ('delit', 'delit'), ('crime', 'crime')], max_length=15, verbose_name='natures du crime')),
                ('descriptionCrime', models.CharField(blank=True, max_length=100, null=True, verbose_name='description crime')),
                ('dateCrime', models.DateField(verbose_name='date du crime ou délit')),
                ('naturePeine', models.CharField(blank=True, choices=[('privation de liberté(emprisonnement)', 'privation de liberté(emprisonnement)'), ('privation ou restriction de droit', 'privation ou restriction de droit')], max_length=100, null=True, verbose_name='nature de la peine')),
                ('durePeine', models.IntegerField(blank=True, null=True, verbose_name='durée des peines')),
                ('observation', models.CharField(default='aucune', max_length=100)),
                ('criminalprofile', models.ManyToManyField(to='gettingApp.CriminalProfil')),
            ],
        ),
    ]
