# Generated by Django 3.2.10 on 2022-09-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gettingApp', '0002_auto_20220902_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crime',
            options={'ordering': ['-dateCondamnation']},
        ),
        migrations.AlterModelOptions(
            name='criminalprofil',
            options={'ordering': ['-name']},
        ),
    ]
