# Generated by Django 3.2.10 on 2022-09-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gettingApp', '0005_auto_20220908_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalprofil',
            name='nationalite',
            field=models.CharField(blank=True, default='nationalité', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='criminalprofil',
            name='profession',
            field=models.CharField(blank=True, default='footbaleur', max_length=100, null=True),
        ),
    ]
