# Generated by Django 3.2.10 on 2022-09-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gettingApp', '0006_auto_20220908_1107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hystorique',
        ),
    ]
